config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'

  namespace :api do
    resources :tags, only: :index
    resources :posts do
      resources :comments
    end
  end

  namespace :dashboard do
    resources :posts do
      member do
        post :publish
        post :hide
      end
      resources :comments
    end
  end

  resources :posts, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  DELETE_TIME = 15 #min

  validates :user_id, :post_id, :body, presence: true
  belongs_to :user
  belongs_to :post

  default_scope { order(created_at: :desc) }
end

app/models/concerns/paginate.rb
module Paginate
  extend ActiveSupport::Concern
  def paginate(options = {})
    default_options = { per_page: 10, page: 1 }
    options = default_options.merge(options)

    options[:page] = 1 if options[:page].nil?
    options[:per_page] = 10 if options[:per_page].nil?

    off_set = (options[:page].to_i * options[:per_page].to_i) - options[:per_page].to_i
    rel = offset(off_set).limit(options[:per_page])
    rel.class.module_eval { attr_accessor :total_pages}

    rel.total_pages = count_pages(options[:per_page])
    rel
  end

  def count_pages(per_page)
    (self.count / per_page.to_f).ceil
  end
end

app/models/concerns/publish.rb
module Publish
  extend ActiveSupport::Concern
  def publish!
    update(hide: false)
  end

  def hide!
    update(hide: true)
  end
end

app/models/concerns/tags.rb
module Tags
  extend ActiveSupport::Concern

  def string_tags=(val)
    self.tags = val.split(',')
  end

  def string_tags
    self.tags ? self.tags.join(',') : self.tags
  end
end

app/models/post.rb
class Post < ApplicationRecord
  include Publish
  include Tags
  extend Paginate

  belongs_to :user
  has_many :comments

  validates :title, :user_id, :body, presence: true

  default_scope { order(created_at: :desc) }
  scope :active, -> { where(hide: false).includes(:comments) }
  scope :by_tag, lambda { |a| where("'#{a}' = ANY (tags)") }

  def self.tags
    Post.active.pluck(:tags).flatten.uniq
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :comments
end

app/controllers/api/application_controller.rb
class Api::ApplicationController < ApplicationController
end

app/controllers/api/comments_controller.rb
class Api::CommentsController < Api::ApplicationController
  before_action :authenticate_user!

  def create
    post = Post.find(params[:post_id])
    post.comments.create(comment_params.merge(user_id: current_user.id))
    redirect_to post_path(post)
  end

  def destroy
    comment = current_user.comments.find(params[:id])
    decorator_comment = CommentDecorator.new(comment)
    @result = decorator_comment.destroy
    head :locked if @result == false
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :post_id)
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < Api::ApplicationController

  def index
    @posts = Post.active.includes(:user)
    @posts = if params[:tag].present?
              @posts.by_tag(params[:tag])
            else
              @posts
            end.paginate(per_page: 5, page: params[:page])  
  end

  def show
    @post = Post.active.find(params[:id])
  end

end

app/controllers/api/tags_controller.rb
class Api::TagsController < Api::ApplicationController
  def index
    tags = Post.tags
    render json: tags.to_json
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  before_filter :init_tags

  private

  def init_tags
    @tags = Post.tags
  end
end

app/controllers/dashboard/application_controller.rb
class Dashboard::ApplicationController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/dashboard/posts_controller.rb
class Dashboard::PostsController < Dashboard::ApplicationController
  before_action :init_post_by_id, only: [:edit, :update, :destroy, :publish, :hide]

  def index
    @posts = current_user.posts
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to dashboard_posts_path, nitice: '.controllers.dashboard.posts.update.success'
    else
      render action: 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to dashboard_posts_path, notice: notice
  end

  def new
    @post = Post.new(tags: '')
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to dashboard_posts_path, notice: I18n.t('.controllers.posts.create.post_was_created')
    else
      render action: 'new'
    end
  end

  def publish
    @post.publish!
    redirect_to dashboard_posts_path
  end

  def hide
    @post.hide!
    redirect_to dashboard_posts_path
  end

  private

  def init_post_by_id
    @post = current_user.posts.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:created_at, :body, :hide, :title, :string_tags)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.active.includes(:user)
    @posts = if params[:tag].present?
              @posts.by_tag(params[:tag])
            else
              @posts
            end.paginate(per_page: 5, page: params[:page])
  end

  def show
    @post = Post.active.find(params[:id])
    @comment = Comment.new(post_id: @post.id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/posts/_form.slim
= form_for([:dashboard, @post], builder: CustomFormBuilder) do |f|
  = f.text_field :title, class: 'form-control'
  = f.text_area :body, class: 'form-control'
  .checkbox
    label
      = f.check_box :hide
      = t('.hide')
  .form-group
    = f.datatime :created_at, class: 'form-control' if @post.persisted?
  .form-group
    = f.tags :string_tags, class: 'form-control'
  = f.submit @post.new_record? ? t('.create') : t('.save')

app/views/dashboard/posts/edit.slim
h1
  = t('.edit_post')
  
= render partial: 'form'

app/views/dashboard/posts/index.slim
.row
  .col-lg-6
    h1
      = t('.my_posts')
  .col-lg-6.text-right 
    = link_to t('.create_post'), new_dashboard_post_path, class: 'btn btn-primary'
    
- if @posts.present?
  table.table.table-hover
    thead
      tr
        th #
        th=t('.post_title')
        th=t('.actions')
    tbody.post_list
      - @posts.each do |post|
        tr
          td
            = post.id
          td
            = post.title
          td.actions
            = link_to t('.delete'), dashboard_post_path(post), method: :delete, data: { confirm: t('.confirm') }, class: 'btn btn-danger btn-xs'
            = link_to t('.edit'), edit_dashboard_post_path(post), class: 'btn btn-primary btn-xs'
            - if post.hide?
              = link_to t('.publish'), publish_dashboard_post_path(post), class: 'btn btn-success btn-xs', method: :post
            - else
              = link_to t('.hide'), hide_dashboard_post_path(post), class: 'btn btn-warning btn-xs', method: :post
      
- else
  h3
    = t('.no_posts')

app/views/dashboard/posts/new.slim
h1
  = t('.new_post')
  
= render partial: 'form'

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "TestApp"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"

  body{class="#{controller_name}_#{action_name}" ng-app="postList"}
    .navbar.navbar-default.navbar-static-top
        .container
          button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand href="#"TestApp
          = render partial: 'shared/navigation'
                
    .container
      .row
        .col-lg-12
          = bootstrap_flash
          = yield
            
        
      footer
        p 
          ' &copy; 
          =' t('.company')
          ' 2016

app/views/posts/index.slim
.row
  .col-xs-8{ng-controller='PostListCtrl'}
    .row
      .col-lg-6
        h1
          = t('.posts')
      - if current_user
        .col-lg-6.text-right 
          = link_to t('.create_post'), new_dashboard_post_path, class: 'btn btn-primary'

    .row.post{ng-repeat="post in posts"}
      .col-xs-12
        .row
          .col-xs-12
        .row
          .col-xs-8
            a{href="{{ post.url }}"}
              | {{ post.title }}
          .col-xs-4
            span
              | Автор
              ' :
            | {{ post.user.email }}
        .row
          .col-xs-12
            span.tags
              | Теги:
            | {{ post.tags }}
    ul.pagination
      li{ng-repeat="i in pages"}
        a{href="#" ng-click='pageChange(i)'}
          | {{i}}
  .col-lg-4
    .row
      .col-xs-12{ng-controller='TagListCtrl'}
        h2
          = t('.tags')
        ul
          li{ng-repeat="tag in tags"}
            a href="#" data-tag="{{tag}}" ng-click="searchByTag($event)"
              | {{ tag }}

app/views/posts/show.slim
.row
  .col-xs-12{ng-app="postList" ng-controller='PostShowCtrl' ng-init="post_id = #{@post.id}; current_user_id = #{current_user ? current_user.id : nil};"}
    h1
      | {{ post.title }}
    .row
      .col-xs-12
        .row
          .col-xs-12
            | {{ post.body }}
        .row.comment{ng-repeat="comment in comments"}
          .col-xs-8
            | {{ comment.body }}
          .col-xs-4.text-right{ng-show="comment.user_id == current_user_id"}
            a{href="" ng-click="deleteComment(comment.id)"}
              | Удалить

        form#new_comment.simple_form.form-horizontal.ng-pristine.ng-valid accept-charset="UTF-8" action="" method="post" novalidate="novalidate" 
          .form-group.text.required.comment_body
            label.control-label.text.required for="comment_body" 
              abbr title="обязательно" *
              | Коментарий
            textarea#comment_body.form-control.text.required name="comment[body]" ng-keyup="hendlerCommentBody($event)" ng-model="comment_body"
          input.btn.btn-default data-disable-with="Создать" name="commit" type="button" value="Создать" ng-click="hendlerCreateComment()" /

app/views/shared/_navigation.slim
.navbar-collapse.collapse.navbar-responsive-collapse
  ul.nav.navbar-nav
    li= link_to t('.main_page'), root_path
    - if current_user
      li
        = link_to t('.my_posts'), dashboard_posts_path
  ul.nav.navbar-nav.navbar-right
    - if current_user
      li
        = link_to t('.log_out'), destroy_user_session_path, method: :delete
    - else
      li
        = link_to t('.registration'), new_user_registration_path
      li
        = link_to t('.sign_in'), new_user_session_path